# Generated by Django 4.2.7 on 2026-03-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='status',
            new_name='_status',
        ),
    ]
